var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/updates/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__072f91db._.js")
R.c("server/chunks/ssr/node_modules_next_dist_4b63a0e1._.js")
R.c("server/chunks/ssr/_b84a4557._.js")
R.c("server/chunks/ssr/[root-of-the-server]__440b7822._.js")
R.c("server/chunks/ssr/node_modules_next_dist_compiled_bc6b8ddf._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_cc94c707._.js")
R.c("server/chunks/ssr/[root-of-the-server]__655f8d11._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__0cac7c9e._.js")
R.c("server/chunks/ssr/lib_0181edcf._.js")
R.c("server/chunks/ssr/app_not-found_tsx_ef35050a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_2fffaa3a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/[root-of-the-server]__fcdb8959._.js")
R.m(16570)
module.exports=R.m(16570).exports
